# 应用名称
spring:
  application:
    name: sharding-database
  main:
    allow-bean-definition-overriding: true
  shardingsphere:
    datasource:
      d1:
        driver-class-name: com.mysql.cj.jdbc.Driver
        password: root
        type: com.alibaba.druid.pool.DruidDataSource
        url: jdbc:mysql://localhost:3306/user_db1?useSSL=false&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
        username: root
      d2:
        driver-class-name: com.mysql.cj.jdbc.Driver
        password: root
        type: com.alibaba.druid.pool.DruidDataSource
        url: jdbc:mysql://localhost:3306/user_db2?useSSL=false&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
        username: root
      names: d1,d2
    props:
      sql:
        show: true
#    sharding:
#      tables:
#        user:
#          actual-data-nodes: d$->{1..2}.user_$->{1..2}
#          database-strategy:
#            inline:
#              ? ''
#                :
#                sharding-column: gender
#              algorithm-expression: d$->{gender=='0'?1:2}
#          key-generator:
#            column: id
#            type: SNOWFLAKE
#          table-strategy:
#            inline:
#              algorithm-expression: user_$->{id% 2 + 1}
#              sharding-column: id

application:
  base-package: com.js
mybatis:
  typeAliasesPackage: ${application.base-package}.pojo, ${application.base-package}.vo, ${application.base-package}.dto
  mapper-locations: classpath:mapper/*/*.xml,classpath:mapper/*.xml
  configuration:
    # 一定要设置，避免个别SQL执行时间过长，把系统搞跨
    default-statement-timeout: 5
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    cache-enabled: false

